scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.gameOver(true)
    game.setGameOverEffect(true, effects.confetti)
    game.setGameOverMessage(true, "\"Hurrah! You Win\"")
})
info.onLifeZero(function () {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    mySprite.setPosition(11, 45)
})
let mySprite: Sprite = null
scene.setBackgroundColor(9)
game.splash("\"MAZE GAME\"")
tiles.setCurrentTilemap(tilemap`level2`)
info.setLife(4)
mySprite = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222234ee............
    ...f222232f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
mySprite.setPosition(11, 45)
controller.moveSprite(mySprite)
let mySprite2 = sprites.create(img`
    . 3 . . . . . . . . . . . 4 . . 
    . 3 3 . . . . . . . . . 4 4 . . 
    . 3 d 3 . . 4 4 . . 4 4 d 4 . . 
    . . 3 5 3 4 5 5 4 4 d d 4 4 . . 
    . . 3 d 5 d 1 1 d 5 5 d 4 4 . . 
    . . 4 5 5 1 1 1 1 5 1 1 5 4 . . 
    . 4 5 5 5 5 1 1 5 1 1 1 d 4 4 . 
    . 4 d 5 1 1 5 5 5 1 1 1 5 5 4 . 
    . 4 4 5 1 1 5 5 5 5 5 d 5 5 4 . 
    . . 4 3 d 5 5 5 d 5 5 d d d 4 . 
    . 4 5 5 d 5 5 5 d d d 5 5 4 . . 
    . 4 5 5 d 3 5 d d 3 d 5 5 4 . . 
    . 4 4 d d 4 d d d 4 3 d d 4 . . 
    . . 4 5 4 4 4 4 4 4 4 4 4 . . . 
    . 4 5 4 . . 4 4 4 . . . 4 4 . . 
    . 4 4 . . . . . . . . . . 4 4 . 
    `, SpriteKind.Enemy)
mySprite2.startEffect(effects.fire)
mySprite2.setPosition(86, 56)
